# Generated by Django 5.1.1 on 2024-11-29 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedwrap',
            name='avg_danceability',
        ),
        migrations.RemoveField(
            model_name='savedwrap',
            name='avg_energy',
        ),
        migrations.RemoveField(
            model_name='savedwrap',
            name='avg_valence',
        ),
        migrations.RemoveField(
            model_name='savedwrap',
            name='recommendations',
        ),
    ]
