# Generated by Django 5.1.1 on 2024-10-23 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0002_alter_userprofile_access_token_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
