# Generated by Django 5.1.1 on 2024-11-04 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify', '0003_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Spotify Wrapped', max_length=255)),
                ('time_range_label', models.CharField(max_length=100)),
                ('total_playback_minutes', models.IntegerField()),
                ('peak_day', models.CharField(blank=True, max_length=100, null=True)),
                ('peak_minutes', models.IntegerField(blank=True, null=True)),
                ('top_genres', models.JSONField()),
                ('top_tracks', models.JSONField()),
                ('avg_danceability', models.FloatField()),
                ('avg_energy', models.FloatField()),
                ('avg_valence', models.FloatField()),
                ('top_artist', models.JSONField(blank=True, null=True)),
                ('top_artists', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
