# Generated by Django 5.1.1 on 2024-11-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedwrap',
            name='peak_day',
        ),
        migrations.RemoveField(
            model_name='savedwrap',
            name='peak_minutes',
        ),
    ]
