# Generated by Django 5.1.1 on 2024-11-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_remove_savedwrap_peak_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedwrap',
            name='time_range_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='savedwrap',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedwrap',
            name='top_artist',
            field=models.JSONField(default=dict),
        ),
    ]
